name: Coordinator

on:
  push:
    branches: [main]
  pull_request:

env:
  COORDINATOR_RPC_URL: "http://localhost:8545"
  COORDINATOR_PUBLIC_KEY_PATH: "./pub.key"
  COORDINATOR_PRIVATE_KEY_PATH: "./priv.key"
  COORDINATOR_TALLY_ZKEY_NAME: "TallyVotes_10-1-2_test"
  COORDINATOR_MESSAGE_PROCESS_ZKEY_NAME: "ProcessMessages_10-20-2_test"
  COORDINATOR_POLL_JOINING_ZKEY_NAME: "PollJoining_10_test"
  COORDINATOR_ZKEY_PATH: "./zkeys/"
  COORDINATOR_RAPIDSNARK_EXE: "~/rapidsnark/build/prover"
  PIMLICO_API_KEY: "pim_"
  RPC_API_KEY: "rpc_"
  SUBGRAPH_FOLDER: "./node_modules/maci-platform-subgraph"
  SUBGRAPH_NAME: ${{ secrets.SUBGRAPH_NAME }}
  SUBGRAPH_PROVIDER_URL: ${{ secrets.SUBGRAPH_PROVIDER_URL }}
  SUBGRAPH_DEPLOY_KEY: ${{ secrets.SUBGRAPH_DEPLOY_KEY }}
  # interface related variables as they are needed for building the monorepo
  NEXT_PUBLIC_CHAIN_NAME: ${{ secrets.NEXT_PUBLIC_CHAIN_NAME }}
  NEXT_PUBLIC_ADMIN_ADDRESS: ${{ secrets.NEXT_PUBLIC_ADMIN_ADDRESS }}
  NEXT_PUBLIC_APPROVAL_SCHEMA: ${{ secrets.NEXT_PUBLIC_APPROVAL_SCHEMA }}
  NEXT_PUBLIC_METADATA_SCHEMA: ${{ secrets.NEXT_PUBLIC_METADATA_SCHEMA }}
  NEXT_PUBLIC_ROUND_ID: ${{ secrets.NEXT_PUBLIC_ROUND_ID }}
  NEXT_PUBLIC_MACI_ADDRESS: ${{ secrets.NEXT_PUBLIC_MACI_ADDRESS }}
  NEXT_PUBLIC_TALLY_URL: ${{ secrets.NEXT_PUBLIC_TALLY_URL }}
  NEXT_PUBLIC_WALLETCONNECT_ID: ${{ secrets.NEXT_PUBLIC_WALLETCONNECT_ID }}
  NEXT_PUBLIC_FEEDBACK_URL: ${{ secrets.NEXT_PUBLIC_FEEDBACK_URL }}
  NEXT_PUBLIC_MACI_START_BLOCK: ${{ secrets.NEXT_PUBLIC_MACI_START_BLOCK }}
  NEXT_PUBLIC_MACI_SUBGRAPH_URL: ${{ secrets.NEXT_PUBLIC_MACI_SUBGRAPH_URL }}
  NEXT_PUBLIC_TOKEN_NAME: ${{ secrets.NEXT_PUBLIC_TOKEN_NAME }}
  NEXT_PUBLIC_MAX_VOTES_TOTAL: ${{ secrets.NEXT_PUBLIC_MAX_VOTES_TOTAL }}
  NEXT_PUBLIC_MAX_VOTES_PROJECT: ${{ secrets.NEXT_PUBLIC_MAX_VOTES_PROJECT }}
  BLOB_READ_WRITE_TOKEN: ${{ secrets.BLOB_READ_WRITE_TOKEN }}
  NEXT_PUBLIC_ALCHEMY_ID: ${{ secrets.NEXT_PUBLIC_ALCHEMY_ID }}
  NEXT_PUBLIC_START_DATE: ${{ secrets.NEXT_PUBLIC_START_DATE }}
  NEXT_PUBLIC_REGISTRATION_END_DATE: ${{ secrets.NEXT_PUBLIC_REGISTRATION_END_DATE }}
  NEXT_PUBLIC_REVIEW_END_DATE: ${{ secrets.NEXT_PUBLIC_REVIEW_END_DATE }}
  NEXT_PUBLIC_VOTING_END_DATE: ${{ secrets.NEXT_PUBLIC_VOTING_END_DATE }}
  NEXT_PUBLIC_RESULTS_DATE: ${{ secrets.NEXT_PUBLIC_RESULTS_DATE }}
  TEST_MNEMONIC: ${{ secrets.TEST_MNEMONIC }}
  WALLET_PRIVATE_KEY: ""

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --yes \
            build-essential \
            libgmp-dev \
            libsodium-dev \
            nasm \
            nlohmann-json3-dev

      - name: Install
        run: |
          pnpm install --frozen-lockfile --prefer-offline

      - name: Build
        run: |
          pnpm run build
        working-directory: packages/coordinator

      - name: Run hardhat
        run: |
          pnpm run hardhat &
          sleep 5
        working-directory: packages/coordinator

      - name: Download rapidsnark (1c137)
        run: |
          mkdir -p ~/rapidsnark/build
          wget -qO ~/rapidsnark/build/prover https://maci-devops-zkeys.s3.ap-northeast-2.amazonaws.com/rapidsnark-linux-amd64-1c137
          chmod +x ~/rapidsnark/build/prover

      - name: Download circom Binary v2.1.6
        run: |
          wget -qO ${{ github.workspace }}/circom https://github.com/iden3/circom/releases/download/v2.1.6/circom-linux-amd64
          chmod +x ${{ github.workspace }}/circom
          sudo mv ${{ github.workspace }}/circom /bin/circom

      - name: Download zkeys
        run: |
          pnpm download-zkeys:latest

      - name: Generate keypair
        run: |
          pnpm generate-keypair
        working-directory: packages/coordinator

      - name: Test
        run: pnpm run test
        working-directory: packages/coordinator

      - name: Stop Hardhat
        if: always()
        run: kill $(lsof -t -i:8545)
